### ISSUE TITLE
DestinationEfsFilesystemId constraint outdated

### ISSUE THREAD

**Issue by Farmbuyer** [aws-samples/amazon-efs-tutorial#21]
The current template in S3 and linked from https://github.com/aws-samples/amazon-efs-tutorial/tree/master/in-cloud-transfer has this parameter entry:

```yaml
  DestinationEfsFilesystemId:
    AllowedPattern: ^(fs-)([a-z0-9]{8})$
    Description: Destination EFS filesystem id.
    Type: String
```

Unfortunately, EFS identifiers have more hex digits than that.  (I suspect they fit in 8 digits at the time the template was last updated.)  Pasting the ID of a perfectly usable EFS instance thus triggers errors when trying to use the template.  :-)

Changing the 8 to 17 (the current number of EFS hex digits) in a local copy of the template was sufficient.
