### ISSUE TITLE
nodejs12.x is no longer a supported runtime

### ISSUE THREAD

**Issue by Farmbuyer** [aws-samples/amazon-efs-tutorial#22]
In the same vein as #11 the template got a little long in the tooth :-)

Fortunately for those of us who don't use Lambda or NodeJS very often, the error message suggested a solution:  specifying nodejs18.x was enough.

```yaml
  AmiInfoFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub solution-references-${AWS::Region}
        S3Key: datasync/amilookup-datasync-agent.zip
      Handler: amilookup-datasync-agent.handler
      Runtime: nodejs18.x
      Timeout: 30
      Role: !GetAtt LambdaExecutionRole.Arn
```
